language: ruby
install: bundle install --jobs=3 --retry=3
rvm:
  - 2.2.4
  - 2.1.8
  - 2.0.0-p648
gemfile:
  - Gemfile
  - ar41.gemfile
  - ar416.gemfile
  - ar50.gemfile
services:
  - mysql
script:
  - bundle exec rake spec
